-- The server craft (hand-built airframe2: 4 thrusters, 2 sails a side
-- below the CoG, ballast to ~73 mass, tables 1/2/3). startup installs this
-- as tune.lua on the computer labelled (or numbered) drone-1; fly loads it
-- over CFG and prints what it took. Values from 2026-09-19:
--   YAW_MAX_LEAN 0.6   the yaw ran away both ways at 45-60 b/s with 0.3
--   YAW_OFFSET 225     puts the lean on the pitch/roll diagonal; 260 put it
--                      mostly on roll and the gimbal let go past ~75 deg
--   CRUISE_DEG 58      62 (13-49) topped out lower at 185, roll swing grew to 60+ deg, thrust
--                      hit the 0.80 cap and it tumbled at 150 b/s: 58 is the ceiling on this frame
--   BRAKE_MAP          31 measured brakes, blocks needed from each speed. The
--                      top points re-fitted 2026-09-19 night: with
--                      BRAKE_TURN_POWER the reversal takes ~2.5 s instead of
--                      ~3.2 and four brakes from 187-192 needed 1039-1146
--                      blocks (23-40-25, 23-47-46). Re-fitted again on
--                      2026-09-20 against the first flights that really flew
--                      58 + the floor: 175 b/s needed 1092-1099, 195 needed
--                      1218, so the top of the map rises with a 175 point.
--                      Mid band raised too: 145-148 b/s needed 913-962
--                      (00-09-35), where the map said 804-833
--   BRAKE_EASE 60      the brake held its full 45 deg lean down to 15 b/s;
--                      below ~85 b/s that saturated the mixer in bursts,
--                      roll missed by 30, yaw kicked to 90 deg/s (13-15-51).
--                      Now it fades below 60 b/s: 30 deg at 40, 15 at 20.
-- Tried and reverted 2026-09-19: YAW_KP/KD 0.01 and CRUISE_AIM_TAU 0.8 each
-- trimmed the cruise yaw swing a little (rms 25 -> 16.5 -> 13.9 deg/s) but
-- roll tracking went 3.8 -> 9.5 -> 11.9 deg rms (flightlogs 13-15-51,
-- 13-27-24, 13-33-44) - back to the default yaw gains and no aim smoothing.
-- 13-57-32 at 58 WITHOUT body lean (tune not yet pulled) tumbled on the
-- return leg: heading error grew to 70 deg from 40 b/s, thrust capped. So
-- 58 is marginal too, and the return leg always wobbles about twice as much.
--   CRUISE_BODY_LEAN 30  lean held on the body while the nose wobbles, so yaw
--                      stops moving the roll command: roll command swing 7.0
--                      -> 3.2 deg, heading error 8.6 -> 6.3, return leg steady
--                      for the first time (14-04-32, 22-38-47, 22-53-13). It
--                      costs ~11 b/s, which is why 62 is worth another go.
--   BRAKE_TURN_POWER   on test from 2026-09-20: 0.55 throttle while the craft
--                      swings from the cruise lean to the brake lean, so the
--                      thrusters keep the torque to turn with. The first 3 s
--                      of a brake from 200 took off only 10-20 b/s
-- 2026-09-19 night, 11 legs measured in 5 s slices: at 58 the roll swing
-- grows slowly and settles around 8-9 deg; at 62 it grows about half as fast
-- again every 5 s (2.6 -> 4.6 -> 7.6 on the calmest leg, 9.6 -> 20.3 on the
-- worst) and tumbled twice. 62 is divergent on this frame, so 58 it is - the
-- good 62 legs were short ones that ended before the swing had grown.
--   LAND_SETTLE_XZ 4   a taxi ride landed 26 blocks from the customer: level
--                      and stopped was enough to start the descent, wherever
--                      it had stopped (02-35-46). Now it closes to 4 blocks
--                      first; LAND_SETTLE_MAX still forces it down after 10 s
--   LAND_SETTLE_MAX 40 the 10 s default ran out on every ride of 2026-09-25:
--                      the brake hands over 45-111 blocks short and already
--                      drifting back at ~10 b/s, closing that takes 12-16 s,
--                      so it dropped 12-33 blocks out still moving 7-13 b/s
--                      and touched down 7-19 off (01-03-25, 01-24-01,
--                      01-40-27). The fall itself can hardly correct (0.12
--                      thrust floor, 8 deg cap, 3 in the flare). 40 s lets
--                      it close to 4 blocks and stop before it drops.
--   LAND_REST_GAP 7.5  the altimeter rests 5.5-7.5 above the pad block (rules
--                      5.5, spawn 6.5, c_district 7.5), and the descent aimed
--                      at the block: every pad landing of 2026-09-25 touched
--                      down 3.5-5.5 blocks before its flare, at 14-18 b/s
--                      (04-02-28, 04-31-17, 04-35-26, 04-38-49). The largest
--                      gap, so the worst case is ~2 s more creep, never an
--                      early contact.
--   BRAKE_MAP          back to the 2026-09-20 map after a one-flight refit
--                      (7986a21, 09-28). The refit read the ~90-block gap at
--                      the end of every brake as stopping SHORT and started
--                      brakes ~65 blocks later. Split along and across the
--                      route, the old map already stopped on the mark along
--                      it (20 flights of the 3,669-block route: median +7,
--                      -76..+121); the gap is SIDEWAYS - the brake swings the
--                      craft 80-130 blocks to the same side every time, from
--                      ~20 off the line at brake start. The first flight on
--                      the refit (07-49-24) ran 198 PAST and took 26 s to
--                      close back, 98.9 s against 88. The sideways swing is
--                      the real target, and it is flight code, not this map.
--   BRAKE_SIDE_K       flown at 1.5 on two flights 2026-09-28, then taken off
--                      so the yaw change below is tested alone. Mixed but
--                      promising: behind a wobbling cruise (08-11-54) it did
--                      nothing - 7-14 b/s sideways, 73 blocks across; behind a
--                      calm one (08-14-15) the brake drifted 31 blocks across
--                      at 2.5 b/s mean, against 61 and 65 at 5.6 and 4.7 on
--                      the last calm returns without it. Put back at 1.5 once
--                      the wobble is settled.
--   YAW_MAX_LEAN       0.8 flown once (08-28-07) and put back to 0.6: the
--                      heading swing got BIGGER (yaw rate 33 deg/s rms late
--                      in the cruise, ~20 normally). The clamp was not the
--                      cause of the wobble - it was capping it.
--   YAW_KD             0.014 TUMBLED on its first flight (2026-09-28 08-32-20),
--                      7.5 s into the cruise: the heading swung from the climb
--                      on, each swing bigger (-25, +17, -19, +16, -40, +54
--                      deg) until 54 deg off with the cruise lean on it
--                      rolled over. The rate term is the heading loop's
--                      damping; the analysis behind 0.014 looked at the rate
--                      loop alone and missed that. Back to fly.lua's 0.02.
--                      The known-good flight after (08-39-44) was clean.
--   YAW_KP 0.01        on test from 2026-09-28 (fly.lua 0.02). Modelled as
--                      the whole loop this time - heading term, rate term and
--                      the 0.3 s delay, with the yaw response fitted from the
--                      logs (79 deg/s^2 per unit of command in the climb, 160
--                      in cruise: it follows the throttle). Phase margin at
--                      KP 0.02: 30 deg in the climb, 16 in cruise with a
--                      1.9 s period - the wobble. KD 0.014 dropped the climb
--                      to 21, the swing that tumbled twice. KP 0.01: 45 in the
--                      climb, 25 in cruise. Alex's read ("yaw P gain too
--                      high"). 0.01 flew on 2026-09-19 and cut the yaw swing
--                      but loosened roll tracking - before CRUISE_BODY_LEAN
--                      took the roll off the yaw. Revert: delete the line.
--                      First flights (08-45-40 and after): calm cruise, yaw
--                      rate ~2.4 deg/s late, heading error 2.2 deg rms (1.0
--                      on 0.02) - a little looser, as expected.
--   CRUISE_DEG 60      on test from 2026-09-28, up from 58 (Alex: "bump speed
--                      before we tune too much"). 62 tumbled on 09-19 with the
--                      thrust at its cap and the roll swinging 60+ deg - on
--                      the old yaw gains, whose wobble was eating the thrust:
--                      calm cruises at 58 peak at 0.56-0.62 throttle, wobbly
--                      ones at 0.75-1.00. Faster cruise means more throttle,
--                      which makes the yaw respond harder and eats some of
--                      the margin KP 0.01 bought - 60, not 62. Revert: 58.
--                      Flown 08-55-38: 184 b/s (172 at 58), throttle 0.59,
--                      yaw calm (2.3 deg/s late, heading 1.9 deg rms), actual
--                      tilt 69 mean / 71.5 peak.
--   CRUISE_DEG 65      on test from 2026-09-28 (Alex: "push it to 65 or
--                      higher"). The actual tilt runs ~9 deg over the lean
--                      (66-67 at 58, 69 at 60), so 65 should sit near 74 and
--                      peak near 77 on a calm cruise - 8 deg under TUMBLE 85,
--                      where fly cuts the thrust. That, not thrust, is the
--                      ceiling: 67 would peak near 80. Expected ~210 b/s.
--                      Revert: 60.
--   BRAKE_MAP 220/235  added for the higher speed: past its last point the map
--                      runs on in a straight line (6.7 blocks per b/s from
--                      190-205), and brake distance grows faster than that, so
--                      the new points are a little steeper - 8 per b/s.
--                      Untried above 205.
--                      Flown 09-02-59: 212 b/s at the brake, still gaining
--                      5.9 b/s^2 (the 3,669-block route is too short to top
--                      out), 79.3 s against ~87, throttle 0.64 (thrusters
--                      0.85). The brake stopped 40 past. But the wobble came
--                      back - yaw rate 17 deg/s late, heading 7.3 rms - and
--                      the tilt ran 75 mean, 82.6 PEAK: 2.4 under TUMBLE 85.
--   YAW_KP 0.005, YAW_KD 0.012  on test from 2026-09-28 (were 0.01 / 0.02),
--                      Alex's call: a plain cut before gain scheduling. The
--                      yaw responds in proportion to throttle (~270 deg/s^2
--                      per unit, 328 at 65 deg), so at 65 the response was 205
--                      against ~95 in the climb, and the phase margin fell to
--                      12 deg. Modelled with the 0.3 s delay: 0.005 / 0.012
--                      gives 50 in the climb, 47 cruising at 58, 38 at 65. Both
--                      gains come down together - the damping-to-heading ratio
--                      stays high, unlike KD 0.014 on KP 0.02, which tumbled.
--                      The cost: a softer yaw everywhere, so a slower turn onto
--                      the heading after takeoff (the cruise waits for it,
--                      CRUISE_YAW_GATE 15 deg, 8 s at most) and a looser heading.
--                      Revert: KP 0.01 and delete the KD line.
--                      Flown 09-13-09: the wobble gone (yaw rate 2.4 deg/s),
--                      heading looser (5.6 rms), climb 2.3 s longer.
--                      (Tilt corrected: the tumble check is per axis, and at
--                      65 pitch peaked 68-69 - 16 clear of 85, not 2.4.)
--   CRUISE_DEG 70      on test from 2026-09-28 (Alex). Pitch should peak near
--                      74 against TUMBLE 85; true tilt near 67. Expect ~235-245
--                      b/s, though 3,669 blocks is too short to reach it. Lift
--                      is the next limit: throttle 0.63 at 65, maybe ~0.75 at
--                      70; ALT_PROTECT pulls the lean cap back if it sinks 15
--                      below. Revert: 65.
--   BRAKE_MAP top      raised with it: both 65 brakes needed more than the map
--                      gave - 1,347 from 213 b/s and 1,383 from 210, against
--                      ~1,320 - and overshot 40 and 84. 205:1310, 220:1450,
--                      235:1590 (~9.3 per b/s from 195's 1,218), and 250:1730
--                      for the extra speed.
--                      Flown 09-42-03: 227 b/s at the brake and still gaining
--                      11 b/s^2, but past the airframe: throttle on its 0.80
--                      ceiling, 15 blocks below cruise height (ALT_PROTECT's
--                      threshold), lean error 8.5 rms (4.7 at 65), pitch peak
--                      76.7. Brake needed 1,591 from 227 against 1,515 - 78
--                      past, 83.8 s against 79.3 at 65 on the same route.
--   CRUISE_DEG 67      from 2026-09-28 (Alex): between 65 (calm, throttle
--                      0.63, room for cargo) and 70 (out of throttle empty).
--   BRAKE_MAP top      refitted to the two measured points above 205: 1,365
--                      from 211 b/s and 1,591 from 227 - about 14 blocks per
--                      b/s up here. 220:1490, 235:1700, 250:1910.
--                      Flown 09-55-21: 215 b/s at the brake, throttle 0.66 (the
--                      0.80 ceiling touched), 7 below cruise height at worst,
--                      pitch peak 71.7, brake 99 SHORT (needed 1,331 from 215 -
--                      brakes up here scatter +-50), 0.9 from the mark, 81.9 s.
--   YAW_KP 0.007       from 2026-09-28 (was 0.005). What yaw was left at 0.005
--                      is a slow wander, not the old 1.8 s swing: yaw rate 3.7
--                      deg/s, heading error 7.9 rms, most of it slow. The
--                      heading comes back in ~KD/KP = 2.4 s, and with 30 deg of
--                      lean held on the body every degree of wander pushes the
--                      craft sideways: 27-42 blocks rms off the centreline at
--                      KP 0.005, 6-13 at 0.01. 0.007 pulls back in 1.7 s with a
--                      modelled 40 deg margin in cruise at 67. If the line is
--                      still more than ~15 blocks rms off, CRUISE_TRACK_K (the
--                      steering back to the centreline, 0.1 b/s per block) is
--                      the next change. Revert: 0.005.
--                      Flown 10-03-51, the first long cruise (6,825 blocks,
--                      96.0 s): 255 b/s and still gaining, height within 7,
--                      throttle 0.68 (on the ceiling 14%), pitch peak 70.5,
--                      heading 6.4 rms (7.9 on 0.005), yaw rate 3.7. Line still
--                      38 rms / 66 worst. Brake 196 SHORT: past 250 the map
--                      ran on in a straight line and asked 1,976 for 1,780.
--   BRAKE_MAP top      refitted 2026-09-28 to all six brakes flown above 205:
--                      1,383 @ 210, 1,347 @ 213, 1,331 @ 215, 1,540 @ 223,
--                      1,591 @ 227, 1,780 @ 256 -> blocks = 9.8 x speed - 700,
--                      scatter +-40-75 (the two at 70 deg sit high). 205:1310,
--                      220:1460, 235:1600, 250:1750, 265:1900.
--                      Flown 10-12-24 (40 short) and 10-18-21 (132 past): the
--                      along-track scatter is the brake's balloon - over 46
--                      brakes the distance beyond the speed fit follows how
--                      high it climbs in the brake (r 0.80). Not the map.
--   BRAKE_SIDE_K 1.5   back on from 2026-09-28, now the wobble is gone. The
--                      brake's sideways swing grows with speed: 55-90 blocks
--                      from ~172 b/s, 130-167 from 214-256 (10-03-51, 10-12-24,
--                      10-18-21), and closing it is most of a 23-31 s approach.
--                      The one calm-cruise flight with it (08-14-15) drifted 31
--                      across against 61 and 65 without. Revert: delete.
--                      Flown 10-24-27: it works - sideways speed in the brake
--                      0.3 b/s mean (2.7-9.3 on the four before), 4 blocks of
--                      sideways drift (43-136), 14 off the line at the end
--                      (73-167). 82.7 s home to the dock, the best there yet.
--                      The approach is now the along-track miss (72 past).
--   BRAKE_HOLD_POWER 0.38  on test from 2026-09-28: a throttle floor through
--                      the steady part of the brake (fly.lua, off by default).
--                      Over 38 brakes from 150+ b/s the deceleration follows
--                      the throttle (r 0.56): 21.6-23.8 b/s^2 at 0.36-0.41,
--                      18.6-18.8 at 0.29-0.30, where the height loop cut it
--                      after a balloon - the long brakes. It lets go 60 above
--                      the goal. The brakes should come out shorter and more
--                      alike; expect the map to need taking down after.
--                      Revert: delete.
--                      Flown 10-31-58 (78.5 s, the best on the standard route;
--                      brake 35 past, decel 21.6, balloon 60) and 10-36-02
--                      (long route, 96.8 s: brake ON the mark along, +1, but
--                      107 across - carried in from the cruise; balloon 67).
--   CRUISE_BODY_LEAN 15  from 2026-09-28, was 30. In every cruise the sideways
--                      acceleration follows the heading error ~0.5 s later
--                      (r -0.83 to -0.94 on six flights): with 30 deg of the
--                      lean held on the body, each degree the nose wanders
--                      tips part of it sideways. The long run (10-36-02) went
--                      93 off the line, came back at 21 b/s and crossed it in
--                      the brake to end 107 out. Body lean went in on 09-19
--                      against a +-40 deg/s yaw wobble; the yaw is ~3 deg/s now.
--                      Alex's call: aim by the centreline, not the nose.
--                      Watch the roll. Revert: 30.
--                      Flown 11-04-00 (69.3 s on the standard route, 78.5 the
--                      best before; approach 7.5 s) and 11-06-56 (long route,
--                      91.0 s): the line held to 11-16 rms / 24-28 worst (30-68
--                      / up to 97 at 30), roll error no worse (4.9-5.7).
--   BRAKE_MAP top      trimmed 2026-09-28 for the throttle floor: floor-on
--                      brakes need 1,393-1,440 from 215-219 b/s and 1,721-1,821
--                      from 262 (the long one balloons more). 11-06-56 stopped
--                      151 short from 263 on 1,880. Fit 1,415 + 7.9 per b/s
--                      over 217: 235:1560, 250:1680, 265:1800 (<=220 unchanged).
--                      Flown on the standard route (12-06-01, 12-22-54): 11
--                      past, 55 short. Body 15 over five flights: line 11, 16,
--                      27, 34, 42 rms - better than 12-68 at 30 but not solved;
--                      three brakes still ended 48-78 to the side.
--   CRUISE_TRACK_K 0.2  from 2026-09-28 (fly.lua 0.1): the pull back to the
--                      centreline, in b/s of sideways demand per block off -
--                      at 40 blocks out, 8 b/s instead of 4. Capped at
--                      CRUISE_TRACK_VMAX 25. Watch for it swinging across the
--                      line. Revert: delete the line.
--                      Flown 12-42-58 onwards: line 14 rms, 14 across after
--                      the brake.
--   BRAKE_MAP low end  refitted 2026-09-28 for short hops. Every brake from
--                      under ~140 b/s on record overshot: the craft is still
--                      accelerating hard (10-17 b/s^2) when the brake starts,
--                      so the swing takes longer, and BRAKE_EASE 60 weakens
--                      anything under 60 b/s. Needed: 484 @ 67 (the 492-block
--                      hop, 153 past), 463-541 @ 77-87 (15 flights), 593-664 @
--                      102-106 (12), 801-831 @ 129-136 (7). 40:300, 55:410,
--                      70:490, 85:520, 105:625, 135:815; 150 up unchanged.
--                      (A later brake could ease off at 20 b/s instead of 60 -
--                      parked for now: the long flights are accurate.)
--   ORDERS_IN_FLIGHT   on 2026-09-29: the admin pocket's Cancel stops the
--                      drone in the air (brakes on the map, hovers, waits 5
--                      min for a new trip, then home), and a new trip for it
--                      in the air turns it round from the hover. Nothing
--                      changes on a flight nobody stops. Revert: delete the line.
--   APPROACH_DECEL 2   on 2026-09-29: the ten flights of 09-29 spent 7-23 s
--                      getting from the brake's end over the pad, most of it
--                      creeping the last 30 blocks (10-54-41: 11 s from 33 to
--                      3 blocks). This asks for a steady 2 b/s^2 slow-down
--                      instead, up to 12 b/s, outside 8 blocks; inside 8 the
--                      hold is as before. Watch: approach time, and that it
--                      still settles and latches. Revert: delete the line.
return {
  APPROACH_DECEL = 2,
  ORDERS_IN_FLIGHT = true,
  YAW_KP = 0.007,
  YAW_KD = 0.012,
  YAW_MAX_LEAN = 0.6,
  BRAKE_EASE = 60,
  YAW_OFFSET = 225,
  CRUISE_DEG = 67,
  CRUISE_BODY_LEAN = 15,
  CRUISE_TRACK_K = 0.2,
  LAND_SETTLE_XZ = 4,
  LAND_SETTLE_MAX = 40,
  LAND_REST_GAP = 7.5,
  BRAKE_TURN_POWER = 0.55,
  BRAKE_SIDE_K = 1.5,
  BRAKE_HOLD_POWER = 0.38,
  BRAKE_MAP = "40:300,55:410,70:490,85:520,105:625,135:815,150:950,175:1100,190:1180,205:1310,220:1460,235:1560,250:1680,265:1800",
}
